### ISSUE TITLE
[question] becoming an official certbot plugin?

### ISSUE THREAD

**Issue by kcris** [Shm013/certbot-dns-freenom#5]
Hi,

Any reason why this plugin shouldn't be part of the official `certbot` package?
Have you tried submitting a pull request?

The ones is see in the official [certbot](https://github.com/certbot/certbot) package have some tests/docs, 
but apart from that, I don't see any special requirements

@Shm013 
Thank you for this plugin, it's really helpful
Chris

**Comment by Shm013** [comment]
Hi!

I started this repo because I couldn't submit a pull request. There was some problems with testing and they don't accept any changes with new plugins.

I'll check if it's possible to merge my plugins into upstream.

Anyway this plugin has end to end test in CI. Docs from [certbot](https://github.com/certbot/certbot) are suitable for this plugin to.

**Comment by Shm013** [comment]
Origin Certbot still not accepting any new DNS plugins.

https://eff-certbot.readthedocs.io/en/stable/contributing.html#writing-your-own-plugin

I'm going to merge this plugin when it will be possibe.
